--- 
default: 
  adapter: postgresql
  database: "<%= ENV.fetch('DB_NAME') { 'schoolay_development' } %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  port: 5432
  timeout: 5000
development: 
  adapter: postgresql
  database: "<%= ENV.fetch('DB_NAME') { 'schoolay_development' } %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  port: 5432
  timeout: 5000
production: 
  adapter: postgresql
  database: "<%= ENV.fetch('DB_NAME') { 'schoolay_development' } %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  port: 5432
  timeout: 5000
staging: 
  adapter: postgresql
  database: "<%= ENV.fetch('TEST_DB_NAME') { 'schoolay_test' } %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  port: 5432  
  timeout: 5000
test: 
  adapter: postgresql
  database: "<%= ENV.fetch('TEST_DB_NAME') { 'schoolay_test' } %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  port: 5432
  timeout: 5000